export const users = [
    { id: 1, username: 'rajesh_kumar', name: 'Rajesh Kumar', email: 'rajesh@example.com', active: true },
    { id: 2, username: 'priya_sharma', name: 'Priya Sharma', email: 'priya@example.com', active: false },
    { id: 3, username: 'aman_singh', name: 'Aman Singh', email: 'aman@example.com', active: true },
    { id: 4, username: 'neha_verma', name: 'Neha Verma', email: 'neha@example.com', active: true },
    { id: 5, username: 'rahul_mehta', name: 'Rahul Mehta', email: 'rahul@example.com', active: true },
    { id: 6, username: 'sneha_patil', name: 'Sneha Patil', email: 'sneha@example.com', active: false },
    { id: 7, username: 'vijay_shukla', name: 'Vijay Shukla', email: 'vijay@example.com', active: true },
    { id: 8, username: 'anita_gowda', name: 'Anita Gowda', email: 'anita@example.com', active: true },
    { id: 9, username: 'sameer_jain', name: 'Sameer Jain', email: 'sameer@example.com', active: true },
    { id: 10, username: 'isha_pandey', name: 'Isha Pandey', email: 'isha@example.com', active: false },
    { id: 11, username: 'arjun_nair', name: 'Arjun Nair', email: 'arjun@example.com', active: true },
    { id: 12, username: 'deepika_shetty', name: 'Deepika Shetty', email: 'deepika@example.com', active: true },
    { id: 13, username: 'siddharth_bansal', name: 'Siddharth Bansal', email: 'siddharth@example.com', active: true },
    { id: 14, username: 'komal_yadav', name: 'Komal Yadav', email: 'komal@example.com', active: false },
    { id: 15, username: 'ankit_mishra', name: 'Ankit Mishra', email: 'ankit@example.com', active: true },
    { id: 16, username: 'puja_choudhary', name: 'Puja Choudhary', email: 'puja@example.com', active: true },
    { id: 17, username: 'rohit_soni', name: 'Rohit Soni', email: 'rohit@example.com', active: true },
    { id: 18, username: 'shivani_kapoor', name: 'Shivani Kapoor', email: 'shivani@example.com', active: false },
    { id: 19, username: 'varun_rathi', name: 'Varun Rathi', email: 'varun@example.com', active: true },
    { id: 20, username: 'ananya_singhal', name: 'Ananya Singhal', email: 'ananya@example.com', active: true },
    { id: 21, username: 'nishant_patel', name: 'Nishant Patel', email: 'nishant@example.com', active: true },
    { id: 22, username: 'ritu_garg', name: 'Ritu Garg', email: 'ritu@example.com', active: false },
    { id: 23, username: 'abhishek_rana', name: 'Abhishek Rana', email: 'abhishek@example.com', active: true },
    { id: 24, username: 'jaya_sharma', name: 'Jaya Sharma', email: 'jaya@example.com', active: true },
    { id: 25, username: 'suresh_gupta', name: 'Suresh Gupta', email: 'suresh@example.com', active: true },
    { id: 26, username: 'pooja_joshi', name: 'Pooja Joshi', email: 'pooja@example.com', active: false },
    { id: 27, username: 'karthik_iyer', name: 'Karthik Iyer', email: 'karthik@example.com', active: true },
    { id: 28, username: 'naina_arora', name: 'Naina Arora', email: 'naina@example.com', active: true },
    { id: 29, username: 'aman_thakur', name: 'Aman Thakur', email: 'amanthakur@example.com', active: true },
    { id: 30, username: 'neelam_shukla', name: 'Neelam Shukla', email: 'neelam@example.com', active: true },
    { id: 31, username: 'praveen_rathore', name: 'Praveen Rathore', email: 'praveen@example.com', active: true },
    { id: 32, username: 'simran_singh', name: 'Simran Singh', email: 'simran@example.com', active: false },
    { id: 33, username: 'vishal_malik', name: 'Vishal Malik', email: 'vishal@example.com', active: true },
    { id: 34, username: 'kavita_choudhary', name: 'Kavita Choudhary', email: 'kavita@example.com', active: true },
    { id: 35, username: 'atul_mehta', name: 'Atul Mehta', email: 'atul@example.com', active: true },
    { id: 36, username: 'deepak_verma', name: 'Deepak Verma', email: 'deepak@example.com', active: true },
    { id: 37, username: 'sonia_mishra', name: 'Sonia Mishra', email: 'sonia@example.com', active: false },
    { id: 38, username: 'manoj_gupta', name: 'Manoj Gupta', email: 'manoj@example.com', active: true },
    { id: 39, username: 'tanya_sharma', name: 'Tanya Sharma', email: 'tanya@example.com', active: true },
    { id: 40, username: 'chirag_singh', name: 'Chirag Singh', email: 'chirag@example.com', active: true },
    { id: 41, username: 'asha_sharma', name: 'Asha Sharma', email: 'asha@example.com', active: false },
    { id: 42, username: 'anil_singh', name: 'Anil Singh', email: 'anil@example.com', active: true },
    { id: 43, username: 'riya_bansal', name: 'Riya Bansal', email: 'riya@example.com', active: true },
    { id: 44, username: 'saurabh_jain', name: 'Saurabh Jain', email: 'saurabh@example.com', active: true },
    { id: 45, username: 'pragati_yadav', name: 'Pragati Yadav', email: 'pragati@example.com', active: true },
    { id: 46, username: 'isha_gupta', name: 'Isha Gupta', email: 'isha@example.com', active: false },
    { id: 47, username: 'nikhil_raj', name: 'Nikhil Raj', email: 'nikhil@example.com', active: true },
    { id: 48, username: 'puja_singh', name: 'Puja Singh', email: 'puja@example.com', active: true },
    { id: 49, username: 'harsh_gupta', name: 'Harsh Gupta', email: 'harsh@example.com', active: true },
    { id: 50, username: 'anjali_kumar', name: 'Anjali Kumar', email: 'anjali@example.com', active: false },
];

export const posts = [
    { id: 1, caption: 'Beautiful sunset', mediaUrl: 'http://example.com/sunset.jpg', published: true },
    { id: 2, caption: 'At the beach', mediaUrl: 'http://example.com/beach.jpg', published: false },
    { id: 3, caption: 'City skyline at night', mediaUrl: 'http://example.com/skyline.jpg', published: true },
    { id: 4, caption: 'A walk in the forest', mediaUrl: 'http://example.com/forest.jpg', published: true },
    { id: 5, caption: 'Delicious food', mediaUrl: 'http://example.com/food.jpg', published: false },
    { id: 6, caption: 'Mountains in winter', mediaUrl: 'http://example.com/mountains.jpg', published: true },
    { id: 7, caption: 'Spring flowers', mediaUrl: 'http://example.com/spring.jpg', published: true },
    { id: 8, caption: 'Rainy day', mediaUrl: 'http://example.com/rain.jpg', published: true },
    { id: 9, caption: 'Family gathering', mediaUrl: 'http://example.com/family.jpg', published: false },
    { id: 10, caption: 'At the amusement park', mediaUrl: 'http://example.com/amusementpark.jpg', published: true },
    { id: 11, caption: 'Road trip memories', mediaUrl: 'http://example.com/roadtrip.jpg', published: true },
    { id: 12, caption: 'Pet day out', mediaUrl: 'http://example.com/pet.jpg', published: true },
    { id: 13, caption: 'Coffee time', mediaUrl: 'http://example.com/coffee.jpg', published: false },
    { id: 14, caption: 'Outdoor adventure', mediaUrl: 'http://example.com/adventure.jpg', published: true },
    { id: 15, caption: 'Stargazing', mediaUrl: 'http://example.com/stars.jpg', published: true },
    { id: 16, caption: 'Concert night', mediaUrl: 'http://example.com/concert.jpg', published: true },
    { id: 17, caption: 'Road trip fun', mediaUrl: 'http://example.com/roadtrip.jpg', published: false },
    { id: 18, caption: 'Sunset at the lake', mediaUrl: 'http://example.com/lake.jpg', published: true },
    { id: 19, caption: 'Beach bonfire', mediaUrl: 'http://example.com/bonfire.jpg', published: true },
    { id: 20, caption: 'Yoga in the park', mediaUrl: 'http://example.com/yoga.jpg', published: true },
    { id: 21, caption: 'Baking day', mediaUrl: 'http://example.com/baking.jpg', published: false },
    { id: 22, caption: 'Visiting the zoo', mediaUrl: 'http://example.com/zoo.jpg', published: true },
    { id: 23, caption: 'Book reading', mediaUrl: 'http://example.com/reading.jpg', published: true },
    { id: 24, caption: 'Cycling in the city', mediaUrl: 'http://example.com/cycling.jpg', published: true },
    { id: 25, caption: 'Friends get-together', mediaUrl: 'http://example.com/friends.jpg', published: true },
    { id: 26, caption: 'Gardening day', mediaUrl: 'http://example.com/gardening.jpg', published: false },
    { id: 27, caption: 'Movie night', mediaUrl: 'http://example.com/movie.jpg', published: true },
    { id: 28, caption: 'Art exhibition', mediaUrl: 'http://example.com/art.jpg', published: true },
    { id: 29, caption: 'Football match', mediaUrl: 'http://example.com/football.jpg', published: true },
    { id: 30, caption: 'Picnic day', mediaUrl: 'http://example.com/picnic.jpg', published: false },
    { id: 31, caption: 'Festival celebrations', mediaUrl: 'http://example.com/festival.jpg', published: true },
    { id: 32, caption: 'Fishing trip', mediaUrl: 'http://example.com/fishing.jpg', published: true },
    { id: 33, caption: 'Exploring the city', mediaUrl: 'http://example.com/exploring.jpg', published: true },
    { id: 34, caption: 'Sunrise view', mediaUrl: 'http://example.com/sunrise.jpg', published: false },
    { id: 35, caption: 'Cooking class', mediaUrl: 'http://example.com/cooking.jpg', published: true },
    { id: 36, caption: 'Shopping day', mediaUrl: 'http://example.com/shopping.jpg', published: true },
    { id: 37, caption: 'Relaxing at home', mediaUrl: 'http://example.com/relaxing.jpg', published: true },
    { id: 38, caption: 'Skiing adventure', mediaUrl: 'http://example.com/skiing.jpg', published: true },
    { id: 39, caption: 'Camping trip', mediaUrl: 'http://example.com/camping.jpg', published: false },
    { id: 40, caption: 'Art class', mediaUrl: 'http://example.com/artclass.jpg', published: true },
    { id: 41, caption: 'Potluck dinner', mediaUrl: 'http://example.com/potluck.jpg', published: true },
    { id: 42, caption: 'Run for charity', mediaUrl: 'http://example.com/charity.jpg', published: true },
    { id: 43, caption: 'Hiking in nature', mediaUrl: 'http://example.com/hiking.jpg', published: true },
];
